### ISSUE TITLE
Memory issues?

### ISSUE THREAD

**Issue by Abhranta** [rahulvigneswaran/TailCalibX#13]
Hello, after training, is TailClaib implemented on the whole dataset at once? Or is it implemented batch-wise? 

If it implemented at once, then it takes up a ridiculous amount of memory and is unable to run. 
While I am implementing it batch-wise, there is a separate issue. There are some batches which only have a single instance in some classes. This gives a zero division error while calculating the co-variance. How to deal with this?

**Comment by rahulvigneswaran** [comment]
Hey @Abhranta 
>Hello, after training, is TailClaib implemented on the whole dataset at once? Or is it implemented batch-wise? If it implemented at once, then it takes up a ridiculous amount of memory and is unable to run.

Hey, the training is supposed to be done on a batch level. Like you said, it will become extremely expensive to do it for the entire dataset. 


> While I am implementing it batch-wise, there is a separate issue. There are some batches which only have a single instance in some classes. This gives a zero division error while calculating the co-variance. How to deal with this?

Can you elaborate a bit more on this?
- [ ] Are you using the pip package or the github code?
- [ ] Can you post post the complete error you are getting?

**Comment by Abhranta** [comment]
Hi, I am posting the full error that I having below. 


---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Cell In[40], line 29
     26 print("labels new - " , y[idx_new])
     28 # Balancing the data using "tailcalib"
---> 29 feat, lab, gen = a.generate(X=inputs_new, y=labels_new)
     31 # Output comparison
     32 print(f"Before: {np.unique(y, return_counts=True)}")

Cell In[24], line 42, in tailcalib.generate(self, X, y, tukey_value, alpha, topk, extra_points, shuffle)
     40 elif self.base_engine == "pytorch":  
     41     import torch
---> 42     return self.generate_usingPyTorch()
     43 else:
     44     raise Exception(f"Invalid base_engine choice - '{self.base_engine}' | Choose from: 'numpy', 'pytorch'.")

Cell In[24], line 155, in tailcalib.generate_usingPyTorch(self)
    153 for i in feat.keys():  
    154     base_means.append(feat[i].mean(dim=0))
--> 155     base_covs.append(self.get_cov(feat[i]).unsqueeze(dim=0))
    157 base_means = torch.vstack(base_means)
    158 base_covs = torch.vstack(base_covs)       

Cell In[24], line 270, in tailcalib.get_cov(self, X)
    267     mu = X.mean(dim=0) 
    268 X = (X - mu) 
--> 270 return 1/(n-1) * (X.transpose(1, 0) @ X)

ZeroDivisionError: division by zero

------------------------------------------------------------------

Some more details - 
1) I am using the long tailed class generator given in the code. 
2) I am using the default PyTorch data loader class. 
3) I am not using the pip package, instead I am using the code for TailCalib.
4) I get the zero division error while starting the tailcalib as I have printed above

**Comment by Abhranta** [comment]
The issue is that there are many classes in a batch which only have 1 instance per class. This is giving the Zero Division error when calculating the co-variance as this leads (n-1)=0 when n=1 and 1/0 is not defined.

**Comment by rahulvigneswaran** [comment]
@Abhranta As you mentioned this issue arises when there is only 1 sample in a class. Moreover, it doesn't make sense to calculate the covariance of a single sample. To bypass this, replace the current `get_cov` with,

```
    def get_cov(self, X):
        """Calculate the covariance matrix for X

        Args:
            X (torch.tensor): Features

        Returns:
            [torch.tensor]: Covariance matrix of X
        """        
        n = X.shape[0]

        # to bypass the error when there is only one sample. 
        # We collect this covariances so that we can sum it up during calibration. 
        # Since covariance doesnt make much sense here, 
        # we are simply borrowing the covariance of nearby classes
        if n == 1:
          return torch.zeros(X.shape[1], X.shape[1]).to(device=X.device)

        if self.base_engine == "numpy":
            mu = X.mean(axis=0) 
        else:
            mu = X.mean(dim=0) 
        X = (X - mu) 

        return 1/(n-1) * (X.transpose(1, 0) @ X)  # X^TX -> feat_size x num_of_samples @ num_of_samples x feat_size -> feat_size x feat_size

```

**Comment by Abhranta** [comment]
Got it !Thanks

**Comment by Angelina1996** [comment]
@Abhranta could you please help me to reproduce the results? I am unable to execute the code due to some errors. Any help will be really appreciated.

Cheers
