### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by Z-ZHHH** [rahulvigneswaran/TailCalibX#3]
`self.batch_forward(inputs, labels, phase="train", retrain=retrain)`
![image](https://user-images.githubusercontent.com/90017146/148639777-bae2cdd9-6b87-49f2-a29d-e3f9a4e02923.png)

**Comment by rahulvigneswaran** [comment]
@Z-ZHHH Thanks for pointing it out. Fixed it.
