### ISSUE TITLE
BUG in TailCalibX.py

### ISSUE THREAD

**Issue by Z-ZHHH** [rahulvigneswaran/TailCalibX#4]
in TailCalibX.py, it inherit the generate_points(self) function, but in that, it cant generate featrue and store for multi-time:
![image](https://user-images.githubusercontent.com/90017146/149060131-23f78840-ed84-4c1a-a330-3a94dd527edc.png)

**Comment by rahulvigneswaran** [comment]
@Z-ZHHH Thanks for pointing it out. It's fixed now.
