### ISSUE TITLE
question about cosineCE

### ISSUE THREAD

**Issue by Z-ZHHH** [rahulvigneswaran/TailCalibX#5]
I have run the CIFAR-100-Imb**100**  experiment_no=**0.2**, i got this results which is different from that in the paper.
CIFAR100 | Imb100 | val-toatal | val-many | val-med | val-few
-- | -- | -- | -- | -- | --
Seed1 | CosineCE | 0.403 | 0.676 | 0.379 | 0.112
Seed2 | CosineCE | 0.403 | 0.670 | 0.396 | 0.101
Seed3 | CosineCE | 0.405 | 0.680 | 0.380 | 0.113
Seed10 | CosineCE | 0.4051 | 0.6737 | 0.3923 | 0.1067
Seed20 | CosineCE | 0.3968 | 0.6754 | 0.3909 | 0.7867
Seed30 | CosineCE | 0.4045 | 0.6811 | 0.378 | 0.1127

<img src="https://user-images.githubusercontent.com/90017146/149289093-2e64cc0b-4ea4-40ba-b21e-fdb939accb7b.png" width="500px">

**Comment by Angelina1996** [comment]
Hi Z-ZHHH, could you please guide how did you execute the code, for me it is generating an error with the following error.
 with open('default_config.yaml') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'default_config.yaml'.
In fact, default_config.yaml file is present in the current directory.
Cheers,
Angelina

**Comment by rahulvigneswaran** [comment]
@Z-ZHHH Sorry about the super delayed reply. We faced similar issues when replicating other paper results too. The cifar100-lt is sketchy and the final results seem very sensitive to randomness. To combat this, we recommend you to use the saved data_target tuples at https://github.com/rahulvigneswaran/TailCalibX/tree/master/libs/data/CIFAR100_LT

**Comment by rahulvigneswaran** [comment]
@Angelina1996 Are you still facing this issue?
