### ISSUE TITLE
`Create_mini-ImageNet-LT.ipynb` missing the txt file

### ISSUE THREAD

**Issue by tcmyxc** [rahulvigneswaran/TailCalibX#6]

**Comment by tcmyxc** [comment]
all_classes.txt, equal_classes.txt, unequal_classes.txt are missing, can not generate the mini-imagenet-lt dataset

**Comment by tcmyxc** [comment]
can you share your `mini-imagenet-lt` dataset?  Thanks.

**Comment by rahulvigneswaran** [comment]
@tcmyxc Sorry about the delayed reply. I am out of town. I will get back to you in a day.

**Comment by xiaomabufei** [comment]
Hello !  Can you share all_classes.txt, equal_classes.txt and unequal_classes.txt? Thanks

**Comment by vpavankalyan** [comment]
Hi @rahulvigneswaran,
I am facing a similar issue as @tcmyxc, can you help with it?

**Comment by Angelina1996** [comment]
Hi Rahul,  Could you plz share all_classes.txt, equal_classes.txt and unequal_classes.txt?
 Thanks

**Comment by Angelina1996** [comment]
Hi Rahul,  Could you plz share all_classes.txt, equal_classes.txt and unequal_classes.txt?
 Thanks

**Comment by Angelina1996** [comment]
Hi guys, just wondering if anyone has fixed that issue.

**Comment by rahulvigneswaran** [comment]
@tcmyxc @Angelina1996 @xiaomabufei @vpavankalyan Sorry about the super delayed response. I have added the required missing assets under https://github.com/rahulvigneswaran/TailCalibX/tree/master/Notebooks/mini-imagenet-assets . Kindly remember to change the directory in the notebook accordingly.
