### ISSUE TITLE
File Not found error

### ISSUE THREAD

**Issue by Angelina1996** [rahulvigneswaran/TailCalibX#8]
Hi, while executing the code, it generates the following error. The file is also present in the current directory. I was just wondering if anyone could help with this.

![image](https://user-images.githubusercontent.com/66866219/183552328-5cfae2da-8174-4627-b470-bdcd0714f884.png)

**Comment by rahulvigneswaran** [comment]
@Angelina1996 Thank you for pointing it out. It's fixed now. Try cloning it again.

**Comment by Angelina1996** [comment]
Thanks, Rahul Vigneswaran, for the reply and for fixing the issue. I also resolved the problem by changing the file's extension from .yaml to .yml. It started working.
