### ISSUE TITLE
The experiments of CE+TailCalib

### ISSUE THREAD

**Issue by madoka109** [rahulvigneswaran/TailCalibX#9]
Thanks for your excellent work!
But I have a question about experiments of CE+TailCalib. I want to find this experiment, but it seems that not including in below.
So how can I find the information about this experiment? Thank you!
![image](https://user-images.githubusercontent.com/79368885/191874214-ed4b7abb-3814-495b-b61a-68afd32d62b8.png)

**Comment by rahulvigneswaran** [comment]
@madoka109 Replacing the settings of 1.2 pretrained part model loading part with the setting of 0.1 and corresponding ce pretrained weight directory in the `experiments_maker.py` will get the experiment you are looking for.
